(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function l(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=l(t);fetch(t.href,r)}})();const n={openModal:function(o){let e=document.querySelector(o);e.addEventListener("click",this.removeModal),e.classList.add("is-open"),e.setAttribute("aria-hidden","false"),document.body.classList.toggle("no-scroll")},closeModal:function(o){let e=document.querySelector(o);e.addEventListener("click",this.removeModal),e.classList.remove("is-open"),e.setAttribute("aria-hidden","true"),document.body.classList.toggle("no-scroll")},openMobileMenu:function(o){let e=document.querySelector(o);e.addEventListener("click",this.removeModal),e.classList.add("is-open"),e.setAttribute("aria-hidden","false"),document.body.classList.toggle("no-scroll")},closeMobileMenu:function(o){let e=document.querySelector(o);e.addEventListener("click",this.removeModal),e.classList.remove("is-open"),e.setAttribute("aria-hidden","true"),document.body.classList.toggle("no-scroll")},removeModal(o){o.target===o.currentTarget&&(o.currentTarget.classList.remove("is-open"),document.body.classList.toggle("no-scroll"))}};let c=function(o){let e=document.querySelectorAll(o),l=1;768<innerWidth&&innerWidth<1280?l=2:innerWidth>1280&&(l=3);for(let s=l;s<e.length;s++)e[s].classList.add("js-load-more")},a=function(o){let e=document.querySelectorAll(o),l=1,s=500;if(e.length!==0)for(let t=0;t<l;t++)setTimeout(()=>{e[t].classList.remove("js-load-more")},s);else document.querySelector(".reviews-btn").innerText="No more reviews!"};globalThis.Modal=n;c(".reviews-list-item");globalThis.loadMore=a;function d(o){document.querySelector(".sale-images-list").addEventListener("click",l=>{console.log(l.target.dataset.src);let s=l.target.dataset.src,t=document.querySelector(".sale-image *"),r=`
        <picture>
            <source srcset="
                ${s}.png,
                ${s}@2x.png 2x
                ">
            <img src="${s}" alt="Preview image">
        </picture>
                `;console.log(r),t.replaceWith(r)})}d();
//# sourceMappingURL=commonHelpers.js.map
